[package]
name = "Selenium_Test_Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
thirtyfour = "0.32.0"
tokio = { version = "1.37.0", features = ["full"] }
